//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.08 at 11:42:06 AM CEST 
//


package datosClases;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for datoscentroType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="datoscentroType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="centro" type="{}centroType"/>
 *         &lt;element name="profesores" type="{}profesoresType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "datoscentroType", propOrder = {
    "centro",
    "profesores"
})
public class DatoscentroType {

    @XmlElement(required = true)
    protected CentroType centro;
    @XmlElement(required = true)
    protected ProfesoresType profesores;

    /**
     * Gets the value of the centro property.
     * 
     * @return
     *     possible object is
     *     {@link CentroType }
     *     
     */
    public CentroType getCentro() {
        return centro;
    }

    /**
     * Sets the value of the centro property.
     * 
     * @param value
     *     allowed object is
     *     {@link CentroType }
     *     
     */
    public void setCentro(CentroType value) {
        this.centro = value;
    }

    /**
     * Gets the value of the profesores property.
     * 
     * @return
     *     possible object is
     *     {@link ProfesoresType }
     *     
     */
    public ProfesoresType getProfesores() {
        return profesores;
    }

    /**
     * Sets the value of the profesores property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProfesoresType }
     *     
     */
    public void setProfesores(ProfesoresType value) {
        this.profesores = value;
    }

}
